#!/usr/bin/env python3
import argparse
import base64
import mimetypes
import re
from datetime import datetime, timezone
from pathlib import Path


def is_remote_or_data_url(value):
    return bool(re.match(r'^(?:https?:)?//', value, re.I)) or bool(re.match(r'^(?:data|mailto|tel):', value, re.I)) or value.startswith('#')


def strip_quotes(value):
    return value.strip().strip('"\'')


def resolve_local(base_file, target):
    clean_target = strip_quotes(target)
    if is_remote_or_data_url(clean_target):
        return None
    return (base_file.parent / clean_target).resolve()


def read_text(file_path):
    return file_path.read_text(encoding='utf-8')


def rel_from_entry(entry_file, file_path):
    try:
        return file_path.relative_to(entry_file.parent)
    except ValueError:
        return Path(file_path).name


def expand_includes(html, current_file, entry_file, seen=None):
    if seen is None:
        seen = set()

    pattern = re.compile(r'<!--\s*@include\s+(.+?)\s*-->')

    def replace(match):
        include_path = resolve_local(current_file, match.group(1))
        if not include_path:
            return match.group(0)
        if include_path in seen:
            raise RuntimeError(f'Circular include detected: {include_path}')

        seen.add(include_path)
        raw = inline_image_assets(read_text(include_path), include_path)
        expanded = expand_includes(raw, include_path, entry_file, seen).strip()
        seen.remove(include_path)

        relative = rel_from_entry(entry_file, include_path)
        return f'<!-- INCLUDE: {relative} START -->\n{expanded}\n<!-- INCLUDE: {relative} END -->'

    return pattern.sub(replace, html)


def inline_styles(html, current_file, entry_file):
    pattern = re.compile(r'<link\b([^>]*?)\bhref=(["\'])([^"\']+)\2([^>]*?)>', re.I)

    def replace(match):
        attrs = f'{match.group(1)} {match.group(4)}'
        is_stylesheet = re.search(r'\brel=(["\'])stylesheet\1', attrs, re.I)
        should_inline = re.search(r'\bdata-inline\b', attrs, re.I)
        if not is_stylesheet or not should_inline:
            return match.group(0)

        css_path = resolve_local(current_file, match.group(3))
        if not css_path:
            return match.group(0)

        css = read_text(css_path).strip()
        relative = rel_from_entry(entry_file, css_path)
        return f'<style data-source="{relative}">\n{css}\n</style>'

    return pattern.sub(replace, html)


def inline_scripts(html, current_file, entry_file):
    pattern = re.compile(r'<script\b([^>]*?)\bsrc=(["\'])([^"\']+)\2([^>]*?)></script>', re.I)

    def replace(match):
        attrs = f'{match.group(1)} {match.group(4)}'
        should_inline = re.search(r'\bdata-inline\b', attrs, re.I)
        if not should_inline:
            return match.group(0)

        script_path = resolve_local(current_file, match.group(3))
        if not script_path:
            return match.group(0)

        js = read_text(script_path).strip()
        relative = rel_from_entry(entry_file, script_path)
        return f'<script data-source="{relative}">\n{js}\n</script>'

    return pattern.sub(replace, html)


def mime_type_for(file_path):
    mime_type, _ = mimetypes.guess_type(str(file_path))
    return mime_type or 'application/octet-stream'


def inline_image_assets(html, current_file):
    pattern = re.compile(r'<img\b[^>]*\bdata-inline-asset\b[^>]*>', re.I)

    def replace(match):
        tag = match.group(0)
        src_match = re.search(r'\bsrc=(["\'])([^"\']+)\1', tag, re.I)
        if not src_match:
            return tag

        asset_path = resolve_local(current_file, src_match.group(2))
        if not asset_path:
            return tag

        encoded = base64.b64encode(asset_path.read_bytes()).decode('ascii')
        data_uri = f'data:{mime_type_for(asset_path)};base64,{encoded}'
        next_tag = tag.replace(src_match.group(0), f'src="{data_uri}"')
        next_tag = re.sub(r'\sdata-inline-asset\b', ' data-inlined-asset', next_tag, flags=re.I)
        return next_tag

    return pattern.sub(replace, html)


def build(input_path, output_path):
    input_path = input_path.resolve()
    output_path = output_path.resolve()

    html = read_text(input_path)
    html = expand_includes(html, input_path, input_path)
    html = inline_styles(html, input_path, input_path)
    html = inline_scripts(html, input_path, input_path)
    html = inline_image_assets(html, input_path)

    banner = '\n'.join([
        '<!--',
        'Generated by vibe-slides-pro-nghienai build_single_html.py',
        f'Source: {input_path}',
        f'Built: {datetime.now(timezone.utc).isoformat()}',
        'Edit source files, then rebuild. Avoid hand-editing this generated file.',
        '-->'
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(f'{banner}\n{html.strip()}\n', encoding='utf-8')
    print(f'Built {output_path}')


def main():
    parser = argparse.ArgumentParser(description='Build a componentized NghienAI slide deck into one HTML file.')
    parser.add_argument('input', help='Path to src/deck.html')
    parser.add_argument('output', help='Path to generated output HTML')
    args = parser.parse_args()
    build(Path(args.input), Path(args.output))


if __name__ == '__main__':
    main()
